<?php
/**
 * 
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function hybridauth_bonus_form_hybridauth_admin_settings_alter(&$form, &$form_state, $form_id) {
  $roles = user_roles(TRUE);
  unset($roles[DRUPAL_AUTHENTICATED_RID]);
  if ($roles) {
    $form['vtabs']['fset_bonus'] = array(
      '#type' => 'fieldset',
      '#title' => t('HybridAuth Bonus'),
    );
    $form['vtabs']['fset_bonus']['hybridauth_registration_role_choice'] = array(
      '#type' => 'checkbox',
      '#title' => t('Suggest role choice when registering'),
      '#description' => t('Allow users to choose their roles when registering through HybridAuth.'),
      '#default_value' => variable_get('hybridauth_registration_role_choice', 0),
    );
    $form['vtabs']['fset_bonus']['hybridauth_registration_roles'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Roles to choose from'),
      '#description' => t('Select roles to suggest to new users when registering through HybridAuth.'),
      '#options' => $roles,
      '#default_value' => variable_get('hybridauth_registration_roles', array()),
      '#states' => array(
        'visible' => array(
          ':input[name="hybridauth_registration_role_choice"]' => array('checked' => TRUE),
        ),
      ),
    );
  }
}

/**
 * Implements hook_hybridauth_registration_form().
 */
function hybridauth_bonus_hybridauth_registration_form($data) {
  if (empty($data['roles']) && variable_get('hybridauth_registration_role_choice', 0)) {
    return TRUE;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function hybridauth_bonus_form_hybridauth_additional_info_form_alter(&$form, &$form_state, $form_id) {
  if (variable_get('hybridauth_registration_role_choice', 0)) {
    //$form['#validate'][] = 'hybridauth_bonus_form_hybridauth_additional_info_form_validate';
    array_unshift($form['#submit'], 'hybridauth_bonus_form_hybridauth_additional_info_form_submit');
    $roles = array_intersect_key(user_roles(TRUE), array_filter(variable_get('hybridauth_registration_roles', array())));
    $form['fset']['roles'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Roles'),
      '#options' => $roles,
    );
  }
}

/*function hybridauth_bonus_form_hybridauth_additional_info_form_validate($form, &$form_state) {
  
}*/

function hybridauth_bonus_form_hybridauth_additional_info_form_submit($form, &$form_state) {
  if (isset($form_state['values']['roles'])) {
    $form_state['values']['data']['roles'] = $form_state['values']['roles'];
    $form_state['values']['data']['manual'][] = 'roles';
  }
}

/**
 * Implements hook_hybridauth_userinfo_alter().
 */
function hybridauth_bonus_hybridauth_userinfo_alter(&$userinfo, $data) {
  if (array_key_exists('roles', $data)) {
    $userinfo['roles'] = $data['roles'];
  }
}
